apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      initContainers:
        - name: wait-for-mongodb
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z mongodb 27017; do echo 'Waiting for MongoDB...'; sleep 2; done",
            ]
      containers:
        - name: user-service
          image: 22i1029/user-service:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_USER
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: MONGO_USER
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: MONGO_PASSWORD
            - name: MONGO_URI
              value: mongodb://$(MONGO_USER):$(MONGO_PASSWORD)@mongodb:27017/?authSource=admin
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: MONGO_DB_USER

---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: todo-app
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
