name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # ✅ Add this step to log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push user-service
        uses: docker/build-push-action@v4
        with:
          context: ./user-service
          push: true
          tags: 22i1131/user-service:latest

      - name: Build and push todo-service
        uses: docker/build-push-action@v4
        with:
          context: ./todo-service
          push: true
          tags: 22i1131/todo-service:latest
