# .github/workflows/cicd.yaml
name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push user-service
        uses: docker/build-push-action@v4
        with:
          context: ./user-service
          push: true
          tags: 22i1029/user-service:latest
      - name: Build and push todo-service
        uses: docker/build-push-action@v4
        with:
          context: ./todo-service
          push: true
          tags: 22i1029/todo-service:latest
